---
language: minimal

dist: xenial

before_install:
  - sudo apt-get install software-properties-common # required by neovim
  - sudo add-apt-repository --yes ppa:neovim-ppa/stable # required by neovim
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get update
  - sudo apt-get install --quiet --yes nodejs
  - sudo apt-get install --quiet --yes neovim
  - sudo apg-get install --quiet --yes python-dev python-pip python3-dev python3-pip # required by neovim
  - sudo apt-get install --quiet --yes yarn

jdk:
  - openjdk11

install:
  - ln -snf $PWD $HOME/.vim
  - make install

script:
  - make test
