---
language: minimal

before_install:
  - sudo add-apt-repository --yes ppa:neovim-ppa/stable
  - sudo apt-get update
  - sudo apt-get install -y neovim
  - sudo apt-get install -y python3 python3-pip
  - sudo apt-get install -y yamllint
  - sudo apt-get install -y nodejs
  - npm install eslint --global

install:
  - make install
