---
language: minimal

before_install:
  - sudo add-apt-repository ppa:neovim-ppa/stable
  - sudo apt-get update
  - sudo apt-get install neovim
  - sudo apt-get install python-neovim
  - sudo apt-get install python3-neovim
