---
language: minimal

before_install:
  - sudo add-apt-repository --yes ppa:neovim-ppa/stable
  - sudo apt-get update
  - sudo apt-get install neovim
  - sudo apt-get install python3 python3-pip
  - sudo apt-get install yamllint

install:
  - make install
