---
language: minimal

before_install:
  - sudo add-apt-repository --yes ppa:neovim-ppa/stable
  - sudo add-apt-repository --yes universe
  - sudo apt-get update
  - sudo apt-get install -y neovim
  - sudo apt-get install -y python2.7 python-pip python-setuptools
  - sudo apt-get install -y python3 python3-pip python3-setuptools
  - sudo apt-get install -y yamllint
  - sudo apt-get install -y npm nodejs
  - sudo apt-get install golang-go
  - sudo npm install eslint --global
  - ln -snf $PWD $HOME/.vim

install:
  - make install

script:
  - make test
