---
language: minimal

before_install:
  - sudo add-apt-repository --yes ppa:neovim-ppa/stable
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get update
  - sudo apt-get install --quiet --yes nodejs
  - sudo apt-get install --quiet --yes neovim
  - sudo apt-get install --quiet --yes python2.7 python-pip python-setuptools
  - sudo apt-get install --quiet --yes python3 python3-pip python3-setuptools
  - sudo apt-get install --quiet --yes yarn

jdk:
  - openjdk11

install:
  - ln -snf $PWD $HOME/.vim
  - make install

script:
  - make test
