---
language: minimal

before_install:
  - sudo add-apt-repository --yes ppa:neovim-ppa/stable
  - sudo apt-get update
  - sudo apt-get install neovim
  - sudo apt-get install python2.7
  - sudo apt-get install python3
  - python2 -m pip install --user --upgrade pynvim
  - python3 -m pip install --user --upgrade pynvim
